name: mobile
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1

  # Network
  dio: ^5.9.0

  # Secure Storage
  flutter_secure_storage: ^9.2.4

  # Routing
  go_router: ^16.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true