spring:
  application:
    name: AuthenticationSystem

  datasource:
    url: jdbc:postgresql://localhost:5433/login_db
    username: admin
    password: securepassword123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  # En az 256-bit (32 byte) uzunluğunda güvenli bir Hex string (Örn: openssl rand -hex 32)
  secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  access-token-expiration: 900000 # 15 dakika (milisaniye)
  refresh-token-expiration: 604800000 # 7 gün (milisaniye)